#!/bin/bash
[[ $1 && $1 != -* ]] && input="-p $1 ${@:2}" || input=$@
cargo run --example svg -- $input -o example.svg -w sites.json
cargo run --example svg -- -p sites.json -c RemoveSitesOutsideBoundingBoxOnly -o orig.svg 1> /dev/null